name: 01-Integration

on:
  push:
    branches:
      - develop
      - main
    
jobs:
  Test_Back_Front:
    uses: ./.github/workflows/01-1-TestBackFront.yml
  
  # Quality_Sonarqube:
  #   needs: [Test_Back_Front]
  #   uses: ./.github/workflows/01-2-QualitySonarqube.yml

  # Security_Snyk:
  #   needs: [Quality_Sonarqube]
  #   uses: ./.github/workflows/01-3-SecuritySnyk.yml